import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { projectCaseView } from "../app/case-view-projections";
import { applyCaseType, caseTypeDefinition } from "../app/case-type-registry";
import type { StudioDraft } from "../app/types";

function matter(): StudioDraft {
  return applyCaseType({
    caseId: "erp_view_case",
    version: "1.0.0",
    parent: null,
    title: "ERP posting incident",
    jurisdiction: "BE",
    role: "Solution architect",
    premise: "A settlement voucher bypassed the expected allocation.",
    classification: { domain: "general", practiceArea: "General legal", difficulty: "Intermediate", tags: [], taxTopics: [], complianceOnly: true },
    nodes: [
      { id: "trigger", type: "trigger", title: "Incident reported", detail: "Finance reports a residual balance.", x: 0, y: 0, runtime: { day: 1, time: "09:00" } },
      { id: "fact", type: "fact", title: "IVCV voucher", detail: "The voucher was generated by inventory close.", x: 0, y: 150 },
      { id: "evidence", type: "evidence", title: "Voucher extract", detail: "The ledger lines retain the source dimensions.", x: 200, y: 150 },
      { id: "decision", type: "decision", title: "Choose remediation", detail: "Compare a ledger rule and direct posting.", x: 100, y: 300, runtime: { day: 2, time: "10:30" } },
      { id: "outcome", type: "outcome", title: "Controlled close", detail: "The residual account is reconciled.", x: 100, y: 470, runtime: { terminalOutcome: "strong" } },
    ],
    links: [
      { id: "fact-decision", from: "fact", to: "decision" },
      { id: "evidence-decision", from: "evidence", to: "decision" },
      { id: "decision-outcome", from: "decision", to: "outcome", rule: { label: "Process ledger allocation", minutes: 90, cost: 1200, result: "Residual balance cleared." } },
    ],
    editHistory: [],
    updatedAt: "2026-08-31T00:00:00.000Z",
  }, "erp_incident");
}

test("v58 projects every ERP view from the same canonical draft", () => {
  const draft = matter();
  assert.deepEqual(caseTypeDefinition(draft.caseType).views, ["task_plan", "evidence_map", "decision_table", "timeline"]);
  const evidence = projectCaseView(draft, "evidence_map");
  assert.equal(evidence.sourceNodeCount, draft.nodes.length);
  assert.deepEqual(evidence.items.map((item) => item.id), ["fact", "evidence"]);
  assert.ok(evidence.items.every((item) => item.status === "ready"));

  const decisions = projectCaseView(draft, "decision_table");
  assert.equal(decisions.items.length, 1);
  assert.equal(decisions.items[0]?.title, "Process ledger allocation");
  assert.equal(decisions.items[0]?.primaryMeta, "Always available");
  assert.equal(decisions.items[0]?.secondaryMeta, "EUR 1,200 · 90 min");

  const timeline = projectCaseView(draft, "timeline");
  assert.equal(timeline.items[0]?.id, "trigger");
  assert.equal(timeline.items[1]?.id, "decision");
  assert.equal(timeline.items.length, draft.nodes.length);
});

test("an unlinked record is visible and explicitly marked for attention", () => {
  const draft = matter();
  draft.nodes.push({ id: "orphan", type: "evidence", title: "Unverified screenshot", detail: "No provenance link yet.", x: 500, y: 100 });
  const item = projectCaseView(draft, "evidence_map").items.find((candidate) => candidate.id === "orphan");
  assert.equal(item?.status, "attention");
  assert.equal(item?.primaryMeta, "Unlinked");
});

test("Developer view keeps a bounded content column and a wrapping action grid", () => {
  const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");
  const app = readFileSync(new URL("../app/JurisApp.tsx", import.meta.url), "utf8");
  assert.match(css, /\.studio-developer-view \.studio-hero\{grid-template-columns:minmax\(340px/);
  assert.match(css, /\.studio-developer-view \.studio-actions\{width:100%;display:grid;grid-template-columns:repeat\(4/);
  assert.match(app, /StudioCaseViews/);
  assert.match(app, /focusGraphNode\(nodeId\)/);
});
