analyzer:
  exclude:
    - build/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - directives_ordering
    - prefer_final_fields
    - prefer_final_locals
    - sort_child_properties_last
    - use_build_context_synchronously
