import type { CaseTypeId, LocalText } from "./types";

const text = (en: string, ru: string): LocalText => ({ en, ru });
const prompts: Record<CaseTypeId, LocalText> = {
  general_advisory: text("Fictional illustration: Harbor is considering a EUR 24,000, 60-day supplier pilot. Compare approval, renegotiation and deferral. Identify the missing acceptance criteria and the evidence needed to test the promised capacity benefit.", "Вымышленный пример: Harbor рассматривает пилот поставщика на 60 дней за 24 000 EUR. Сравните одобрение, пересмотр условий и отсрочку. Укажите недостающие критерии приёмки и доказательства для проверки обещанного роста мощности."),
  litigation_strategy: text("Fictional illustration: Northline has EUR 48,000 in unpaid invoices; EUR 12,000 is disputed for delays. Compare settlement with a claim. List missing receipt evidence and the deadlines counsel must verify before a final demand.", "Вымышленный пример: Northline имеет неоплаченные счета на 48 000 EUR; 12 000 EUR оспариваются из-за задержек. Сравните соглашение с предъявлением требования. Укажите недостающие подтверждения получения и сроки, которые юрист должен проверить до окончательного требования."),
  contract_review: text("Fictional illustration: Cloudbridge's SaaS renewal costs EUR 36,000 annually. Review the restoration exclusion and missing data-export deadline. Propose negotiation priorities and identify residual risks requiring the service owner's acceptance.", "Вымышленный пример: продление SaaS Cloudbridge стоит 36 000 EUR в год. Проверьте исключение восстановления данных и отсутствие срока выгрузки. Предложите приоритеты переговоров и укажите остаточные риски, требующие согласования владельца сервиса."),
  tax_planning: text("Fictional illustration: compare annual tax costs of EUR 100,000 and EUR 80,000 over 36 months, with EUR 25,000 implementation and EUR 5,000 annual maintenance. Assess net benefit and downside costs; flag unverified tax eligibility before recommending implementation.", "Вымышленный пример: сравните годовые налоговые затраты 100 000 и 80 000 EUR за 36 месяцев при внедрении за 25 000 EUR и сопровождении за 5 000 EUR в год. Оцените чистую выгоду и рост затрат; отметьте непроверенное право на налоговый режим до рекомендации о внедрении."),
  compliance: text("Fictional illustration: two of Clearpath's three sampled supplier controls have approval records; the access review lacks sign-off. Draft a remediation plan with an owner, retest evidence and an activation gate. Distinguish policy requirements from operating evidence.", "Вымышленный пример: два из трёх проверенных контролей поставщика Clearpath согласованы; проверка доступа не подписана. Составьте план устранения с ответственным, доказательствами повторной проверки и условием активации. Отделите требования политики от доказательств работы контроля."),
  tax_compliance: text("Fictional illustration: Meridian plans EUR 120,000 in annual intercompany service payments across two unspecified jurisdictions. Prepare a reporting-readiness checklist covering pricing support, allocation, local obligations and owners. Keep unknown deadlines and tax treatment unresolved pending local advice.", "Вымышленный пример: Meridian планирует внутригрупповые платежи за услуги на 120 000 EUR в год в двух неуказанных юрисдикциях. Составьте чек-лист готовности отчётности: обоснование цены, распределение, местные обязанности и ответственные. Не определяйте неизвестные сроки и налоговый режим до местной консультации."),
  erp_incident: text("Fictional illustration: Atlas batch B-17 posted 12 invoice lines twice after a retry. Propose containment, reconciliation and a repeatable retry test. Preserve original logs and treat the idempotency-key failure as a hypothesis until reproduced.", "Вымышленный пример: пакет Atlas B-17 дважды провёл 12 строк счетов после повторного запроса. Предложите локализацию, сверку и повторяемый тест повторного запроса. Сохраните исходные журналы; считайте сбой ключа идемпотентности гипотезой до воспроизведения."),
  investigation: text("Fictional illustration: five Beacon expense claims share an approval screenshot whose timestamp conflicts with the export log. Separate supported findings from hypotheses, list provenance checks and request the original approval record. Do not infer intent from the discrepancy alone.", "Вымышленный пример: пять заявок Beacon используют один скриншот согласования, время которого расходится с журналом выгрузки. Отделите подтверждённые выводы от гипотез, перечислите проверки происхождения и запросите оригинал согласования. Не выводите умысел только из расхождения."),
  training_simulation: text("Fictional illustration: Signal's import service is down and a restart may erase temporary logs. In Test → Play, choose a response, then explain which evidence supports recovery and which safeguards your route preserves or loses. Review the debrief before changing the scenario.", "Вымышленный пример: сервис импорта Signal недоступен; перезапуск может удалить временные журналы. В «Тест → Играть» выберите действие и объясните, какие доказательства подтверждают восстановление и какие контроли ваш маршрут сохраняет или теряет. Изучите разбор до изменения сценария."),
};

/** Editable instructions only; not recorded facts or approved outputs. */
export function categoryDemoPrompt(id: CaseTypeId, locale: "en" | "ru"): string {
  return prompts[id][locale];
}
