export const helpContent = {
  en: {
    guides: [
      ["Start with a brief, template or file", "In Case Studio, describe the decision, your role, jurisdiction, deadline, known facts and desired outcome. Templates start a fresh draft with intake questions; Demo contains fictional examples. Before replacing current work, preserve it. For an ordinary brief, use Import case or prompt and review the proposed structure before applying it."],
      ["Restore an exact case file", "For a complete canonical Markdown export, choose Verify canonical case, inspect the preview, then Apply exact case. Keep the entire file, including its embedded data. A normal prompt is not an exact restoration. Import opens a draft; it does not confirm a workspace save."],
      ["Review the structure and evidence", "Give the case a clear title. Use Overview → Sources & evidence → Decision → Review → Reports. Open Brief & structure to edit the brief or review proposed changes. Check proposed facts, alternatives and outcomes before accepting them. Separate verified evidence, estimates and missing information. The Next step card helps you continue; it is not a review or approval."],
      ["Save, wait for confirmation, then reopen", "Use Save to workspace. Sign in and complete your profile if prompted. Wait for Saved to workspace, then open My cases → Personal with the same account and check the saved content in a separate tab. Further edits need another confirmed save. Keep the original tab until you have verified the saved copy."],
      ["Find personal and team work", "Personal contains your account-owned Studio cases. Team contains governed organization records: select the correct organization and permissions. Importing or saving a personal draft does not create a Team record. A browser draft or downloaded case file is stored separately from both collections."],
      ["Inspect the actual report", "Choose Create analytical report, then Preview PDF or Download PDF. Open the downloaded file and check the title, facts, evidence, alternatives and unresolved conditions. A download-started message does not confirm receipt. Saving, file verification and PDF export do not independently approve a decision."],
    ],
    faq: [
      ["Where are my cases after moving to casevant.pro?", "Sign in again with the same account and open My cases → Personal. For Team, select the same organization. Sessions and device-only drafts belong to the earlier domain. Keep that tab in the same browser/profile, save there and wait for confirmation, or use a permitted export. Follow the recovery instructions below before closing the original."],
      ["Do I need AI to create or edit a case?", "You can enter and review the case manually. AI-assisted preparation requires the account, completed profile and service access requested by the interface. If it is unavailable, keep your brief and continue with manual editing. Review any proposed structure before applying it."],
      ["Are Demo and Templates duplicates?", "Demo contains fictional walkthroughs and decision simulations. Templates create a fresh Studio draft with a case type and intake questions; they do not copy a demo's facts, documents or conclusions."],
      ["Why does canonical verification fail?", "Use the complete exported Markdown file, not copied visible text. If embedded data or the fingerprint is missing or mismatched, obtain an intact export. Do not treat ordinary text as an exact restoration."],
      ["What if sign-in or saving is unavailable?", "Keep the current tab and a permitted export. Use Account on the published site. If the page fails, report its address, time and displayed error without sending credentials or private evidence. Opening another domain does not transfer an unsaved draft."],
      ["What if saving times out?", "Keep the original tab. Open Personal cases separately and inspect the most recent saved content before retrying: an uncertain response does not prove the write failed. Preserve a permitted export; report the case reference, operation and displayed error if the result remains uncertain."],
      ["What if the PDF does not appear?", "Check the browser's downloads and popup settings, then try Preview PDF. Open the actual file to confirm it arrived. Keep the case open and report the displayed error if it persists."],
      ["What does the CaseVant training cover?", "The 10-minute course was rebuilt for CaseVant on 5 October 2026, with current navigation, English narration, captions and transcript. It combines a real CaseVant opening screen with labeled workflow illustrations. Account saves, AI and Team creation are instructions, not recordings of completed actions. Check the inputs in your own case."],
    ],
  },
  ru: {
    guides: [
      ["Начните с задачи, шаблона или файла", "В Студии опишите решение, свою роль, юрисдикцию, срок, известные факты и желаемый результат. Шаблоны создают новый черновик с вопросами, Демо содержит вымышленные примеры. Сохраните текущую работу перед заменой. Для обычного текста используйте «Импортировать кейс или промпт» и проверьте предложенную структуру перед применением."],
      ["Восстановите точный кейс из файла", "Для полного канонического экспорта Markdown выберите «Проверить канонический кейс», изучите результат и примените точный кейс. Нужен весь файл со встроенными данными. Обычный промпт не восстанавливает кейс точно. Импорт открывает черновик и не подтверждает сохранение в аккаунте."],
      ["Проверьте структуру и материалы", "Дайте кейсу понятное название. Используйте «Обзор → Источники и факты → Решение → Проверка → Отчёты». Откройте «Задача и структура» для описания и проверки изменений. Проверяйте факты, альтернативы и исходы перед принятием. Разделяйте доказательства, оценки и неизвестные данные. Карточка «Следующий шаг» помогает продолжить работу, но не означает проверку или утверждение."],
      ["Сохраните, дождитесь подтверждения и откройте снова", "Сохраните кейс в рабочем пространстве. При необходимости войдите и заполните профиль. Дождитесь статуса «Сохранено в workspace», затем откройте «Мои кейсы → Личные» в том же аккаунте и проверьте содержимое в отдельной вкладке. Новые правки требуют нового подтверждённого сохранения. До проверки копии оставьте исходную вкладку открытой."],
      ["Найдите личные кейсы и дела команды", "«Личные» содержит кейсы Studio вашего аккаунта. «Команда» — дела организации с её правилами доступа: выберите нужную организацию. Импорт и сохранение личного черновика не создают дело команды. Черновик браузера и скачанный файл хранятся отдельно от обеих коллекций."],
      ["Проверьте сам отчёт", "Выберите «Создать аналитический отчёт», затем просмотр или скачивание PDF. Откройте скачанный файл и проверьте название, факты, доказательства, варианты и нерешённые условия. Начало загрузки не подтверждает получение файла. Сохранение, проверка файла и экспорт PDF сами по себе не утверждают решение."],
    ],
    faq: [
      ["Где мои кейсы после перехода на casevant.pro?", "Войдите заново в тот же аккаунт и откройте «Мои кейсы → Личные». Для дел команды выберите прежнюю организацию. Сеанс входа и локальные черновики привязаны к старому домену. Оставьте старую вкладку в том же браузере и профиле, сохраните кейс с подтверждением или сделайте разрешённый экспорт. Перед закрытием оригинала следуйте инструкции перехода ниже."],
      ["Обязательно ли использовать AI?", "Кейс можно заполнять и проверять вручную. Для подготовки с AI нужны аккаунт, заполненный профиль и доступ к сервису, указанные в интерфейсе. Если функция недоступна, сохраните описание задачи и продолжите ручное редактирование. Проверяйте предложенную структуру перед применением."],
      ["Демо и Шаблоны — одно и то же?", "Демо содержит вымышленные пошаговые примеры и симуляции решений. Шаблоны создают новый черновик с типом кейса и вопросами, без фактов, документов и выводов демо."],
      ["Не проходит проверка канонического файла", "Используйте полный экспорт Markdown со встроенными данными, а не скопированный видимый текст. Если данные или контрольная сумма отсутствуют либо не совпадают, получите неповреждённый экспорт. Обычный текст не является точным восстановлением."],
      ["Не работают вход или сохранение", "Оставьте текущую вкладку и сохраните разрешённый экспорт. Откройте «Аккаунт» на опубликованном сайте. Сообщите адрес страницы, время и текст ошибки без пароля и частных материалов. Открытие другого домена не переносит несохранённый черновик."],
      ["Сохранение зависло", "Оставьте исходную вкладку. Отдельно откройте личные кейсы и проверьте последнее содержимое перед повтором: неопределённый ответ не доказывает, что запись не состоялась. Сохраните разрешённый экспорт. Если результат неясен, сообщите ссылку на кейс, действие и показанную ошибку."],
      ["PDF не появился", "Проверьте загрузки и настройки всплывающих окон, затем попробуйте просмотр PDF. Откройте сам файл, чтобы подтвердить получение. Оставьте кейс открытым и сообщите показанную ошибку, если она повторяется."],
      ["Что входит в обучение CaseVant?", "Десятиминутный курс пересобран для CaseVant 5 октября 2026: актуальная навигация, английская озвучка, субтитры и расшифровка. Реальный начальный экран CaseVant дополнен обозначенными иллюстрациями. Сохранение, AI и создание дела команды объясняются как инструкции, а не запись выполненных действий. Проверяйте значения своего кейса."],
    ],
  },
} as const;
