"use client";

import { useRef, useState } from "react";
import type { StudioOverviewProps } from "./StudioOverview";
import { openStudioSourceFragment, studioOverview, studioSourceFragmentId } from "./studio-overview";
import { studioGovernedEvidenceDestination } from "./studio-governed-evidence";
import { useWorkspaceLocation } from "./use-interface-locale";
import styles from "./studio-overview.module.css";

export default function StudioSourcesPanel({ draft, locale, onStep, onNode, onAction }: StudioOverviewProps) {
  const model = studioOverview(draft, locale);
  const evidenceDestination = studioGovernedEvidenceDestination(useWorkspaceLocation());
  const root = useRef<HTMLElement>(null);
  const [notice, setNotice] = useState("");
  const t = (en: string, ru: string) => locale === "en" ? en : ru;
  const records = [...model.facts, ...model.evidence];
  function jump(document: string, version: number, section: string) {
    const opened = root.current && openStudioSourceFragment(root.current, studioSourceFragmentId(document, version, section));
    setNotice(opened ? "" : t("That exact reference section is unavailable. No substitute version has been opened.", "Точный фрагмент недоступен. Другая версия не была подставлена."));
  }
  return <section ref={root} className={styles.workspace} aria-labelledby="studio-sources-title">
    <header className={styles.header}><div><p className={styles.eyebrow}>{t("CASE MATERIALS", "МАТЕРИАЛЫ ДЕЛА")}</p><h2 id="studio-sources-title">{t("Sources and evidence", "Источники и материалы")}</h2></div><span className={styles.status}>{t("Review not recorded here", "Проверка здесь не зафиксирована")}</span></header>
    <dl className={styles.counts}><div><dt>{t("Reference documents", "Эталонные документы")}</dt><dd>{model.documentCount ?? t("Not attached", "Не приложены")}</dd></div><div><dt>{t("Fact / evidence records in graph", "Записи фактов / материалов на схеме")}</dt><dd>{model.recordedCount}{model.requiredRecordCount !== null ? ` / ${model.requiredRecordCount}` : ""}</dd></div><div><dt>{t("Human-reviewed grounds", "Основания, проверенные человеком")}</dt><dd>{t("Not recorded in Studio", "Не фиксируются в Studio")}</dd></div></dl>
    <p className={styles.muted}>{model.documentCount !== null ? t("The nine fictional documents and their retained versions are reference material. The graph record count measures structure, not the number of uploaded documents or accepted facts. Presence, connection and human review are separate.", "Девять вымышленных документов и сохранённые версии — эталонные материалы. Счётчик записей показывает структуру графа, а не число загруженных документов или принятых фактов. Наличие, связь и человеческая проверка различаются.") : t("Studio stores authored graph records and text references. Uploaded document versions, reviewed assertions and exact evidence anchors belong to the case evidence workflow; no such review is inferred here.", "Studio хранит записи графа и текстовые ссылки. Версии документов, проверенные утверждения и точные ссылки на доказательства находятся в процессе проверки дела; здесь их проверка не предполагается.")}</p>
    {notice && <p role="alert" className={styles.notice}>{notice}</p>}

    <section className={styles.block}><h3>{t("Recorded facts and evidence", "Записанные факты и материалы")}</h3>{records.length ? <ul className={styles.records}>{records.map(node => <li key={node.id}><span className={styles.muted}>{node.type === "fact" ? t("Authored fact record", "Авторская запись факта") : t("Evidence record", "Запись материала")}</span><h4>{node.title}</h4><p>{node.detail}</p><button type="button" onClick={() => onNode(node.id)}>{t("Inspect this graph record", "Открыть запись на схеме")}</button></li>)}</ul> : <p>{t("No fact or evidence graph records are present.", "На схеме пока нет записей фактов или материалов.")}</p>}<button type="button" onClick={() => onAction ? onAction({ step: 3, id: "studio-evidence-composer", nodeType: "evidence" }) : onStep(3)}>{t("Add a connected working record", "Добавить связанную рабочую запись")}</button></section>
    <section className={styles.block} aria-labelledby="studio-governed-evidence-title">
      <h3 id="studio-governed-evidence-title">{t("Facts, assumptions and review", "Факты, допущения и проверка")}</h3>
      <p>{t("Organization cases provide source versions, typed assertions and review in Evidence.", "В разделе «Доказательства» дела организации доступны версии источников, типы утверждений и проверка.")}</p>
      <p>{evidenceDestination.returning
        ? t("Return to the organization case you came from. This Studio draft remains separate; opening its evidence does not copy or link the draft's records.", "Вернитесь в дело организации, из которого открыли Studio. Этот черновик остаётся отдельным: переход не копирует и не связывает его записи.")
        : t("Choose the intended case in My cases → Team, then open Evidence. Studio does not infer a matching organization case or copy your draft into it.", "Выберите нужное дело в «Мои кейсы → Команда», затем откройте «Доказательства». Studio не подбирает дело организации и не копирует в него черновик.")}</p>
      <a className={styles.actionLink} href={evidenceDestination.href}>{evidenceDestination.returning ? t("Return to the originating case's evidence", "Вернуться к доказательствам исходного дела") : t("Choose an organization case", "Выбрать дело организации")}</a>
    </section>
    {model.references.length > 0 && <section className={styles.block}><h3>{t("Text references in the working model", "Текстовые ссылки в рабочей модели")}</h3><p>{t("These references open the retained fictional source section. They are not accepted dossier anchors or proof of an unchanged source-to-conclusion dependency.", "Ссылки открывают сохранённый фрагмент вымышленного источника. Это не принятые ссылки дела и не доказательство неизменной зависимости вывода от источника.")}</p><ul className={styles.references}>{model.references.map(ref => <li key={`${ref.nodeId}:${ref.document}:${ref.version}:${ref.section}`}><button type="button" onClick={() => onNode(ref.nodeId)}>{draft.nodes.find(node => node.id === ref.nodeId)?.title ?? ref.nodeId}</button><span>{ref.document} v{ref.version} § {ref.section}</span>{ref.source ? <button type="button" onClick={() => jump(ref.document, ref.version, ref.section)}>{t("Open exact reference passage", "Открыть точный фрагмент")}</button> : <strong>{t("Exact source/version/section unavailable", "Точный источник, версия или фрагмент недоступны")}</strong>}{!ref.exactTextPresent && <p>{t("The full reference excerpt is not present verbatim in this graph record. Reconcile the text before relying on the relationship.", "Полный фрагмент источника не совпадает дословно с записью. Сопоставьте тексты перед использованием связи.")}</p>}</li>)}</ul></section>}
    {model.sourcePacket.length > 0 && <section className={styles.block}><h3>{t("Retained fictional source packet", "Сохранённый пакет вымышленных источников")}</h3><p>{t(`${model.documentCount} document identities · ${model.sourcePacket.length} immutable versions. Open the version cited by the record; a later version does not silently replace it.`, `Документов: ${model.documentCount}; неизменяемых версий: ${model.sourcePacket.length}. Открывайте указанную в записи версию: новая версия не подставляется автоматически.`)}</p>{model.sourcePacket.map(source => <details className={styles.source} key={`${source.id}:${source.version}`}><summary>{source.id} v{source.version} — {source.title}</summary>{Object.entries(source.sections).map(([section, text]) => <div className={styles.fragment} tabIndex={-1} id={studioSourceFragmentId(source.id, source.version, section)} key={section} lang="en"><h4>§ {section}</h4><p>{text}</p></div>)}</details>)}</section>}
    {model.documentCount === null && <section className={styles.block}><h3>{t("Text references only", "Только текстовые ссылки")}</h3>{draft.classification?.sourceUrls?.length ? <ul>{draft.classification.sourceUrls.map((url, index) => <li key={`${index}:${url}`}><code>{url}</code></li>)}</ul> : <p>{t("No separate source URLs are recorded. Node explanations remain available in the decision map.", "Отдельные URL источников не записаны. Пояснения узлов доступны на карте решений.")}</p>}<p>{t("A text URL is not an uploaded document, exact citation or human verification.", "Текстовый URL не является загруженным документом, точной цитатой или человеческой проверкой.")}</p></section>}
  </section>;
}
